services:
  db:
    container_name: telegrambot-db
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

  bot:
    image: eclipse-temurin:21-jre-jammy
    container_name: telegrambot
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./target/TelegramBot-1.5.jar:/app/bot.jar
      - ./subscriptions.json:/app/subscriptions.json
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    command:
      [
        "java",
        "-jar",
        "bot.jar",
        "--subscription.jsonFilePath=/app/subscriptions.json"
      ]
    restart: unless-stopped

volumes:
  pgdata:
