spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  task:
    scheduling:
      enabled: true
      pool:
        size: 3
      thread-name-prefix: "scheduler-"
    execution:
      enabled: true
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 100
      thread-name-prefix: "async-"

server:
  port: ${APP_PORT:8080}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    firstAdminId: ${TELEGRAM_FIRST_ADMIN_ID}
    secondAdminId: ${TELEGRAM_SECOND_ADMIN_ID}
  subscription:
    vpnSubName: ${VPN_SUB_NAME}
    vpnPriceValue: ${VPN_PRICE_VALUE}
    vpnPaymentDay: ${VPN_PAYMENT_DAY}
    appleSubName: ${APPLE_SUB_NAME}
    applePriceValue: ${APPLE_PRICE_VALUE}
    applePaymentDay: ${APPLE_PAYMENT_DAY}
